apiVersion: batch/v1
kind: Job
metadata:
  name: wrk
spec:
  parallelism: 3
  completions: 6
  template:
    metadata:
      name: wrk

    spec:
      containers:
      - name: wrkr
        image: zilman/wrk
        env:
        - name: SCRIPT
          value: "/wrk/post.lua"
        - name: DURATION
          value: "30"
        - name: CONNECTIONS
          value: "10"
        - name: THREADS
          value: "2"
        - name: TIMEOUT
          value: "10"
        - name: URL
          value: "http://countly.cncfdemo.io/i?begin_session=1&app_key="
      restartPolicy: Never
