apiVersion: batch/v1
kind: Job
metadata:
  name: wrk
spec:
  parallelism: 3
  completions: 3
  template:
    metadata:
      name: wrk

    spec:
      containers:
      - name: wrkr
        image: zilman/wrk
        env:
        - name: DURATION
          value: "10"
        - name: CONNECTIONS
          value: "10"
        - name: THREADS
          value: "2"
        - name: TIMEOUT
          value: "3"
        - name: URL
          value: "http://countly.cncfdemo.io/i?begin_session=1&app_key=6e42e649bf67b5e8651d5fb7e4b27d7af21411bb"
      restartPolicy: Never
