apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'

      # Override the global default and scrape targets from this job every 5 seconds.
        scrape_interval: 5s

        target_groups:
          - targets: ['localhost:9090']


