apiVersion: v1
kind: Service
metadata:
  labels:
    name: distcc
  name: distcc
spec:
  selector:
    app: distcc
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: distcc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: distcc
  template:
    metadata:
      name: distcc
      labels:
        app: distcc
    spec:
      containers:
      - name: distcc
        image: zilman/distcc:latest
