apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wrkr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wrkr
    spec:
      containers:
      - name: wrkr
        image: zilman/wrk
        env:
        - name: DURATION
          value: "10"
        - name: CONNECTIONS
          value: "4"
        - name: THREADS
          value: "2"
        - name: TIMEOUT
          value: "3"
        - name: URL
          value: ""


