apiVersion: v1
kind: Service
metadata:
  name: mongoc
  labels:
    app: mongoc
spec:
  ports:
  - port: 27017
    name: mongoc
  clusterIP: None
  selector:
    app: mongoc
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: cfg
spec:
  serviceName: mongoc
  replicas: 3
  template:
    metadata:
      labels:
        app: mongoc
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: mongo
        image: mongo:3.2
        command: 
        - mongod
        - "--configsvr"
        - "--replSet"
        - configs
        - "--bind_ip"
        - 0.0.0.0
        ports:
        - containerPort: 27017
          name: mongoc
---
apiVersion: v1
kind: pods
conditional: all([item['status']['phase'] == 'Running' for item in resp['items']])
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongoc
---
apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: mng
spec:
  autoSelector: true
  template:
    metadata:
      name: mng
    spec:
      containers:
      - name: mng
        image: mongo:3.2
        command: ["mongo", "--host", "cfg-0.mongoc", "--port", "27019", "--eval", "rs.initiate({_id: 'configs', members: [{'_id':0,host:'cfg-0.mongoc:27019'},{'_id':1,host:'cfg-1.mongoc:27019'},{'_id':2,host:'cfg-2.mongoc:27019'}]})"]
      restartPolicy: Never

