apiVersion: v1
kind: ReplicationController
metadata:
  name: chat
spec:
  replicas: 2
  selector:
    name: chat
  template:
    metadata:
      labels:
        name: chat
    spec:
      containers:
      - name: redis
        image: zilman/socketio:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "0.1"

